# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking
        - !!!
    - title: FEATURE
      labels:
        - Semver-Minor
        - feature
        - Feature
    - title: TASK
      labels:
        - Semver-Minor
        - task
        - Task
    - title: BUGFIX
      labels:
        - Semver-Minor
        - bugfix
        - Bug
    - title: Other Changes
      labels:
        - "*"
