version: 2.1

general:
  branches:
    only:
      - 8.3
      - 8.4

# disabled starting with Neos 9.0 and to be removed eventually. Kept as we keep the CI hook active for Neos 8.x

jobs:
  noop:
    docker:
      - image: cimg/node:20.9-browsers
    steps:
      - run: node --version

workflows:
  version: 2
  noop-wf:
    jobs:
      - noop:
          filters:
            tags:
              only:
                - /never/
            branches:
              only:
                - /never/
