export const DOCUMENT_ADD_CONFIGURATION = 'DOCUMENT_ADD_CONFIGURATION';
export const DOCUMENT_APPLY_CHANGE = 'DOCUMENT_APPLY_CHANGE';

export const NODE_ADD = 'NODE_ADD';
export const NODE_ADD_BULK = 'NODE_ADD_BULK';
