export const DOCUMENT_ADD_CONFIGURATION = 'DOCUMENT_ADD_CONFIGURATION';
export const DOCUMENT_APPLY_CHANGE = 'DOCUMENT_APPLY_CHANGE';

export const NODE_ADD = 'NODE_ADD';
export const NODE_ADD_BULK = 'NODE_ADD_BULK';

export const CHANGE_ADD = 'CHANGE_ADD';
export const CHANGES_CLEAR = 'CHANGES_CLEAR';
