export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_TAB_METADATA = 'SET_TAB_METADATA';
export const UPDATE_TAB_WORKSPACE_INFO = 'UPDATE_TAB_WORKSPACE_INFO';
export const REMOVE_TAB = 'REMOVE_TAB';
export const CREATE_TAB = 'CREATE_TAB';

export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
