export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_TAB_METADATA = 'SET_TAB_METADATA';
export const UPDATE_TAB_WORKSPACE_INFO = 'UPDATE_TAB_WORKSPACE_INFO';
export const REMOVE_TAB = 'REMOVE_TAB';
export const CREATE_TAB = 'CREATE_TAB';

export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';

export const TOGGLE_OFF_CANVAS = 'TOGGLE_OFF_CANVAS';
export const HIDE_OFF_CANVAS = 'HIDE_OFF_CANVAS';

export const REMOTE_SAVING_START = 'REMOTE_SAVING_START';
export const REMOTE_SAVING_FINISH = 'REMOTE_SAVING_FINISH';
export const REMOTE_PUBLISHING_START = 'REMOTE_PUBLISHING_START';
export const REMOTE_PUBLISHING_FINISH = 'REMOTE_PUBLISHING_FINISH';
export const REMOTE_DISCARDING_START = 'REMOTE_DISCARDING_START';
export const REMOTE_DISCARDING_FINISH = 'REMOTE_DISCARDING_FINISH';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const REMOVE_FLASH_MESSAGE = 'REMOVE_FLASH_MESSAGE';
