##
# Backend

-
  name:  'Backend'
  uriPattern: 'neos/<BackendSubRoutes>'
  defaults:
    '@package':    'Neos.Neos.Ui'
    '@action':     'index'
    '@format':     'html'
  subRoutes:
    'BackendSubRoutes':
      package: 'Neos.Neos.Ui'
      suffix:  'Backend'

##
# Service

-
  name:  'Backend'
  uriPattern: 'neos/ui-services/<ServiceSubRoutes>'
  defaults:
    '@package':    'Neos.Neos.Ui'
    '@action':     'index'
    '@format':     'html'
  subRoutes:
    'ServiceSubRoutes':
      package: 'Neos.Neos.Ui'
      suffix:  'Service'

-
  name: 'GetReferencesSummary Query'
  uriPattern: 'neos/references-editor/get-references-summary'
  defaults:
    '@package': 'Neos.Neos.Ui'
    '@subpackage': 'ReferencesEditor\Application\GetReferencesSummary'
    '@controller': 'GetReferencesSummary'
    '@action': 'ignored'

-
  name: 'GetChildrenForTreeNode Query'
  uriPattern: 'neos/references-editor/get-children-for-tree-node'
  defaults:
    '@package': 'Neos.Neos.Ui'
    '@subpackage': 'ReferencesEditor\Application\GetChildrenForTreeNode'
    '@controller': 'GetChildrenForTreeNode'
    '@action': 'ignored'

-
  name: 'GetTree Query'
  uriPattern: 'neos/references-editor/get-tree'
  defaults:
    '@package': 'Neos.Neos.Ui'
    '@subpackage': 'ReferencesEditor\Application\GetTree'
    '@controller': 'GetTree'
    '@action': 'ignored'

-
  name: 'GetNodeSummary Query'
  uriPattern: 'neos/references-editor/get-node-summary'
  defaults:
    '@package': 'Neos.Neos.Ui'
    '@subpackage': 'ReferencesEditor\Application\GetNodeSummary'
    '@controller': 'GetNodeSummary'
    '@action': 'ignored'
