name: E2E (Client, Server)
on:
  workflow_dispatch:
  push:
    branches: [ main, '[0-9]+.[0-9]' ]
  pull_request:
    branches: [ main, '[0-9]+.[0-9]' ]

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: "Browser Tests"
    runs-on: ubuntu-latest

    env:
      FLOW_CONTEXT: Production
      DISTRIBUTION_FOLDER: neos-distribution
      PACKAGE_FOLDER: Neos.Neos.Ui

    defaults:
      run:
        working-directory: ${{ env.DISTRIBUTION_FOLDER }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.3'
            neos-version: '9.0'

    services:
      mariadb:
        # see https://mariadb.com/kb/en/mariadb-server-release-dates/
        # this should be a current release, e.g. the LTS version
        image: mariadb:10.6
        env:
          MYSQL_USER: neos
          MYSQL_PASSWORD: neos
          MYSQL_DATABASE: neos
          MYSQL_ROOT_PASSWORD: neos
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.PACKAGE_FOLDER }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql

      - name: Checkout development distribution
        uses: actions/checkout@v4
        with:
          repository: neos/neos-development-distribution
          ref: ${{ matrix.neos-version }}
          path: ${{ env.DISTRIBUTION_FOLDER }}

      - name: Cache Composer packages
        uses: actions/cache@v4
        timeout-minutes: 30
        with:
          path: |
            ~/.cache/composer
            ${{ env.DISTRIBUTION_FOLDER }}/Packages
          key: php-${{ matrix.php-version }}-neos-${{ matrix.neos-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-neos-${{ matrix.neos-version }}-

      - name: Prepare Neos.Neos.Ui Package for composer installation
        run: |
          cd "../${{ env.PACKAGE_FOLDER }}"
          # no "neos/neos-ui-compiled" because this job recompiles JS
          composer remove neos/neos-ui-compiled --no-update
          # install also export-ignore'd Test/ and packages/ directory
          rm .gitattributes

      - name: Install and link composer dependencies
        run: |
          composer config --no-plugins allow-plugins.neos/composer-plugin true
          composer config repositories.package '{ "type": "path", "url": "../${{ env.PACKAGE_FOLDER }}", "options": { "symlink": false } }'
          composer config repositories.testsites '{ "type": "path", "url": "../${{ env.PACKAGE_FOLDER }}/Tests/IntegrationTests/TestDistribution/DistributionPackages/*", "options": { "symlink": false } }'
          composer require --no-update --no-interaction neos/neos-ui:@dev
          composer require --no-update --no-interaction neos/test-onedimension:@dev
          composer require --no-update --no-interaction neos/test-twodimensions:@dev
          composer require --no-update --no-interaction neos/test-nodetypes:@dev

          composer install --no-interaction --no-progress --prefer-dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '${{ env.DISTRIBUTION_FOLDER }}/Packages/Application/Neos.Neos.Ui/.nvmrc'
          cache-dependency-path: '${{ env.DISTRIBUTION_FOLDER }}/Packages/Application/Neos.Neos.Ui/yarn.lock'
          cache: 'yarn'

      - name: Install npm dependencies
        run: |
          cd Packages/Application/Neos.Neos.Ui
          make install

      - name: Build for js for e2e
        run: |
          cd Packages/Application/Neos.Neos.Ui
          make build-e2e-testing

      - name: Setup Flow
        run: |
          rm -f Configuration/Settings.yaml
          cat <<EOF >> Configuration/Settings.yaml
          Neos:
            Flow:
              persistence:
                backendOptions:
                  host: '127.0.0.1'
                  driver: pdo_mysql
                  user: 'neos'
                  password: 'neos'
                  dbname: 'neos'

            Neos:
              Ui:
                frontendDevelopmentMode: true
          EOF
          ./flow
          ./flow doctrine:migrate

      - name: Setup Testing Neos Sites and Users
        run: |
          ./flow cr:setup --content-repository onedimension
          ./flow site:pruneAll --content-repository onedimension --force --verbose
          ./flow site:importAll --content-repository onedimension --package-key Neos.Test.OneDimension --verbose

          ./flow cr:setup --content-repository twodimensions
          ./flow site:pruneAll --content-repository twodimensions --force --verbose
          ./flow site:importAll --content-repository twodimensions --package-key Neos.Test.TwoDimensions --verbose

          ./flow user:create --username=admin --password=admin --first-name=Admin --last-name=Admington --roles=Administrator || true
          ./flow user:create --username=editor --password=editor --first-name=Editor --last-name=McEditworth --roles=Editor || true

      - name: Start flow server (in background)
        run: |
          echo 127.0.0.1 onedimension.localhost | sudo tee -a /etc/hosts
          echo 127.0.0.1 twodimensions.localhost | sudo tee -a /etc/hosts
          chmod 777 Web/
          ./flow resource:publish
          ./flow server:run --port 8081 &

      - name: Setup Sauce connect and CTL
        run: |
          # https://docs.saucelabs.com/secure-connections/sauce-connect-5/installation/linux/
          curl -L -o sauce-connect.deb https://saucelabs.com/downloads/sauce-connect/5.3.0/sauce-connect_5.3.0.linux_amd64.deb
          sudo dpkg -i sauce-connect.deb

          npm install -g saucectl

      - name: Start e2e tunnel (in background)
        run: |
          sc run --tunnel-name "neos-tunnel" --region "us-west-1" --proxy-localhost allow &

      - name: Run e2e tests
        run: |
          cd Packages/Application/Neos.Neos.Ui
          saucectl run --config .sauce/config.yml --tunnel-name "neos-tunnel" --region "us-west-1" --artifacts.download.directory ../../../Data/Logs/saucelabs-artifacts

      - name: Show Testcafe output
        if: ${{ always() }}
        shell: bash
        run: |
          for file in Data/Logs/saucelabs-artifacts/**/console.log; do
            echo $file
            cat $file
          done

      - name: Assert no Flow exceptions swallowed
        if: ${{ always() }}
        shell: bash
        run: |
          if [ ! -d "Data/Logs/Exceptions" ]; then
            exit 0
          fi

          for file in Data/Logs/Exceptions/*; do
            echo $file
            cat $file
            echo "\n"
            echo "\n"
          done

          exit 1

      - name: Show Flow logs on failure
        if: ${{ failure() }}
        shell: bash
        run: |
          for file in Data/Logs/*.log; do
            echo $file
            cat $file
            echo "\n"
            echo "\n"
          done

      # enable to debug container (https://upterm.dev)
      # - name: Setup ssh session for debugging
      #   if: ${{ failure()  }}
      #   uses: owenthereal/action-upterm@v1
      #   with:
      #     wait-timeout-minutes: 5
